name: lint and e2e tests for pull requests
on:
  pull_request:

permissions:
  contents: write

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: pnpm/action-setup@v6
        with:
          version: 10

      - uses: actions/setup-node@v6
        with:
          node-version: 24.18.0
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: biome (linter and formatter)
        run: |
          pnpm biome:fix
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore: format and lint fix with Biome [skip ci]"
            git push
            exit 0
          fi

      - name: typescript
        run: pnpm type:check

      - name: prepare component tests
        run: pnpm storybook &
  
      - name: prepare component and E2E tests (install playwright)
        run: |
          pnpm playwright install
          pnpm playwright install-deps

      - name: component tests
        run: |
          pnpx wait-on tcp:6006
          pnpm test:storybook --url http://localhost:6006

      - name: prepare E2E tests (start next app)
        run: |
          pnpm build
          pnpm start &
        env:
          NEXT_PUBLIC_BASE_URL: http://localhost:3000

      - name: E2E test
        run: pnpm test:playwright

      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: playwright-report
          path: playwright/playwright-report/
          retention-days: 1
