name: lint and e2e tests for pull requests
on:
  pull_request:

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20.1.0
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: biome (linter and formatter)
        run: pnpm biome:check

      - name: typescript
        run: pnpm type:check

      - name: prepare component tests
        run: pnpm storybook &
  
      - name: prepare component and E2E tests (install playwright)
        run: |
          pnpm playwright install
          pnpm playwright install-deps

      - name: component tests
        run: |
          pnpx wait-on tcp:6006
          pnpm test:storybook --url http://localhost:6006

      - name: prepare E2E tests (start next app)
        run: |
          pnpm build
          pnpm start &
        env:
          NEXT_PUBLIC_BASE_URL: http://localhost:3000

      - name: E2E test
        run: pnpm test:playwright

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright/playwright-report/
          retention-days: 1
